"""Target family for the truncated-collision ladder (salted synthetic messages only).

Every target is a fixed triple (digest function, truncation width, 16-byte salt). The salt is derived
deterministically from the target name, so records.json can be regenerated byte-for-byte on any machine:

    python problems/hash_collision_prize/records.py --write

``--write`` also measures ``reference.baseline_seconds`` with the trusted seed solver (median of 3 seeds,
seeds 1/2/3) and stores null plus a note for any target whose median run exceeds MEASURE_CAP_SECONDS.
``reference.expected_hashes`` is the birthday estimate sqrt(pi/2) * 2^(bits/2) for the truncated function.

No instance file exists: the whole instance is the (function, rounds, bits, salt) tuple in records.json,
which is staged read-only into the worker next to verify.py.
"""

import hashlib
import json
import os
import statistics
import sys


HERE = os.path.dirname(os.path.abspath(__file__))
RECORDS = os.path.join(HERE, "records.json")
SCHEMA_VERSION = 1
SALT_BYTES = 16
MEASURE_CAP_SECONDS = 120.0
MEASURE_SEEDS = (1, 2, 3)

# name, digest function, compression rounds (None = full), truncation bits
_SPECS = (
    ("sha256-t28-dev", "sha256", None, 28),
    ("sha256-t32-dev", "sha256", None, 32),
    ("sha256-t36-dev", "sha256", None, 36),
    ("ripemd160-t32-dev", "ripemd160", None, 32),
    ("sha256-t32-hold", "sha256", None, 32),
    ("sha256-t36-hold", "sha256", None, 36),
    ("ripemd160-t32-hold", "ripemd160", None, 32),
    ("sha256r24-t32-hold", "sha256-reduced", 24, 32),
    ("sha256-t40-large", "sha256", None, 40),
    ("sha256-t44-large", "sha256", None, 44),
    ("ripemd160-t36-large", "ripemd160", None, 36),
    ("ripemd160-t40-large", "ripemd160", None, 40),
)

DEVELOPMENT = [name for name, _, _, _ in _SPECS if name.endswith("-dev")]
HOLDOUT = [name for name, _, _, _ in _SPECS if name.endswith("-hold")]
LARGE_TARGETS = [name for name, _, _, _ in _SPECS if name.endswith("-large")]
ALL_TARGETS = [name for name, _, _, _ in _SPECS]


def salt_for(name):
    """Deterministic per-target salt: the first 16 bytes of sha256("hash_collision_prize:salt:<name>")."""
    seed = f"hash_collision_prize:salt:{name}".encode("utf-8")
    return hashlib.sha256(seed).digest()[:SALT_BYTES].hex()


def expected_hashes(bits):
    """Birthday expectation for a collision in a uniform b-bit range: sqrt(pi/2) * 2^(b/2)."""
    return (3.141592653589793 / 2) ** 0.5 * 2.0 ** (bits / 2.0)


def _spec(name, function, rounds, bits):
    return {
        "name": name,
        "function": function,
        "rounds": rounds,
        "bits": bits,
        "salt": salt_for(name),
        "reference": {
            "baseline_seconds": None,
            "expected_hashes": expected_hashes(bits),
            "note": "baseline not measured",
        },
    }


def _defaults():
    return {name: _spec(name, function, rounds, bits) for name, function, rounds, bits in _SPECS}


def _validate(table, where):
    missing = [name for name in ALL_TARGETS if name not in table]
    if missing:
        raise RuntimeError(f"hash_collision_prize records {where}: targets missing: {missing}")
    for name, function, rounds, bits in _SPECS:
        spec = table[name]
        if (spec.get("function"), spec.get("rounds"), spec.get("bits")) != (function, rounds, bits):
            raise RuntimeError(f"hash_collision_prize records {where}: {name} does not match the declared spec")
        if spec.get("salt") != salt_for(name):
            raise RuntimeError(f"hash_collision_prize records {where}: {name} carries an unexpected salt")
    return table


def table():
    """{name: spec} from the committed records.json, falling back to unmeasured defaults."""
    if os.path.exists(RECORDS):
        data = json.load(open(RECORDS))
        return _validate(data.get("targets", {}), "cache")
    return _defaults()


def resolve(target):
    """Accept either a target name or an already loaded spec dict and return the spec."""
    if isinstance(target, dict):
        for key in ("function", "bits", "salt"):
            if key not in target:
                raise KeyError(f"target spec is missing {key!r}")
        return target
    return load_target(target)


def load_target(name):
    """Spec for one target name."""
    known = table()
    if name not in known:
        raise KeyError(f"unknown target {name!r}")
    return known[name]


def load():
    """{name: baseline seconds} -- the reference the loop scores a candidate's solve time against."""
    return {name: spec["reference"].get("baseline_seconds") for name, spec in table().items()}


def fetch():
    """There is no live table to fetch; re-measure locally with ``--write`` instead."""
    return load()


def _measure(name, cap=MEASURE_CAP_SECONDS):
    """Median wall seconds over MEASURE_SEEDS of the trusted seed solver, or (None, note) when it is too slow."""
    import time

    sys.path.insert(0, HERE)
    import seed_solver  # CLI-only: seed_solver is never staged into the worker, so this import stays local

    spec = load_target(name)
    times = []
    for seed in MEASURE_SEEDS:
        started = time.time()
        result = seed_solver.solve(spec, budget=cap, seed=seed)
        elapsed = time.time() - started
        if result is None or elapsed > cap:
            return None, f"no collision within {cap:g}s on seed {seed}; baseline left unmeasured"
        times.append(elapsed)
    return round(statistics.median(times), 3), f"median of {len(times)} seed solver runs (seeds {list(MEASURE_SEEDS)})"


def write(cap=MEASURE_CAP_SECONDS, measure=True):
    """Regenerate records.json: deterministic specs plus freshly measured baselines."""
    targets = _defaults()
    for name, spec in targets.items():
        if not measure:
            continue
        seconds, note = _measure(name, cap=cap)
        spec["reference"]["baseline_seconds"] = seconds
        spec["reference"]["note"] = note
        print(f"  {name:20} baseline={seconds if seconds is not None else 'null':>8}  {note}")
    payload = {
        "schema_version": SCHEMA_VERSION,
        "development": DEVELOPMENT,
        "holdout": HOLDOUT,
        "large": LARGE_TARGETS,
        "targets": targets,
    }
    with open(RECORDS, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(payload, handle, indent=1, allow_nan=False, sort_keys=False)
        handle.write("\n")
    return payload


if __name__ == "__main__":
    if "--write" in sys.argv:
        write(measure="--no-measure" not in sys.argv)
    else:
        for name, spec in table().items():
            reference = spec["reference"]
            print(
                f"  {name:20} {spec['function']:>14} rounds={spec['rounds']} bits={spec['bits']:3} "
                f"expected_hashes={reference['expected_hashes']:.3e} baseline={reference['baseline_seconds']}"
            )
