"""Public data for the ECDLP research ladder (problems/ecc_prize/records.json).

The ladder is ten prime-field curves generated offline and deterministically by curves.py, mirroring
the shape of the Certicom ECCp-131 challenge instance (y^2 = x^3 + a*x + b over F_p, prime order n,
cofactor 1) at sizes this lab can actually finish. records.json holds only PUBLIC data -- p, a, b, n,
the generator P and the challenge point Q -- plus a per-target ``reference`` block whose
``baseline_seconds`` is the median wall time the seed solver needed on the authoring machine. The
discrete logarithm of each instance is never written anywhere: the verifier only needs to recompute
k*P and compare it with Q.

There is no network here. ``fetch()`` simply re-reads the committed file; new instances are produced
by ``python problems/ecc_prize/curves.py --write``.
"""

import hashlib
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RECORDS = os.path.join(HERE, "records.json")

# Development is what generation prompts may name; HOLDOUT is the confirmation set and stays hidden.
DEVELOPMENT = ["ecdlp-p24-dev", "ecdlp-p28-dev", "ecdlp-p32-dev", "ecdlp-p36-dev"]
HOLDOUT = ["ecdlp-p28-hold", "ecdlp-p32-hold", "ecdlp-p36-hold", "ecdlp-p40-hold"]
# Opt-in heavy rungs, selectable only through ``--targets`` (loop.py honours LARGE_TARGETS).
LARGE_TARGETS = ["ecdlp-p44-large", "ecdlp-p48-large"]
TARGETS = list(DEVELOPMENT)
ALL_TARGETS = DEVELOPMENT + HOLDOUT + LARGE_TARGETS
BITS = {name: int(name.split("-")[1][1:]) for name in ALL_TARGETS}

# sha256 of each target's canonical public tuple (name, bits, p, a, b, n, P, Q). This is the code-level
# anchor for records.json: table() refuses a file whose instances do not hash to these values, so a
# swapped or edited curve cannot reach the verifier unnoticed. Regenerate together with the ladder via
# ``python problems/ecc_prize/curves.py --write``, which rewrites the block below in place.
# DIGESTS-BEGIN (generated by curves.py --write; do not edit by hand)
DIGESTS = {
    "ecdlp-p24-dev": "6eb99bb52085096588107c65a02addda69d22fa8d934c14470a51f0a6b7c5229",
    "ecdlp-p28-dev": "54580dadfb04ea602fe31595a1e43675be71be70fd7af3ff7bbd4ebc2d2fb81b",
    "ecdlp-p32-dev": "03f97315a56a6f54c235de72bfe98e3b09ceb9c4232e9ea3a755a35d00bd8481",
    "ecdlp-p36-dev": "5dbc542361abcc318b9d8a4795a64c7c3d9832cba5f85064666bc9b6a0183396",
    "ecdlp-p28-hold": "f5d564484625df09837186d66e32441fae16de839db4f1d2e7b1261f33d4bd5f",
    "ecdlp-p32-hold": "fadf6aa08bd9dcaf098882ae927d5d57c48cdcbfdc718d5831efe9d9f536a467",
    "ecdlp-p36-hold": "044d89350e13046be4bf8d4f0e2ef62bf730fe5f8abf1d6a2f91fd765c0e9269",
    "ecdlp-p40-hold": "b8a20578a3742feeb2f35904d6495595266ad5581777135210db282a4b084632",
    "ecdlp-p44-large": "d05f7cb2f720684e1967427e7e05f1aa28b3023ee6eaa1413d9fe3f0e9b80c02",
    "ecdlp-p48-large": "dd6c2073ebfdff84e6b1b0add18989fab3564c6e72e28718819f61a514ca12ad",
}
# DIGESTS-END

_CACHE = None


def digest_for(instance):
    """sha256 over the canonical JSON of one instance's public tuple (name, bits, p, a, b, n, P, Q)."""
    public = [
        instance["name"],
        instance["bits"],
        instance["p"],
        instance["a"],
        instance["b"],
        instance["n"],
        [instance["P"][0], instance["P"][1]],
        [instance["Q"][0], instance["Q"][1]],
    ]
    return hashlib.sha256(json.dumps(public, separators=(",", ":")).encode("utf-8")).hexdigest()


def _validate(document):
    """Every declared target present and hashing to its committed digest, or RuntimeError."""
    instances = document.get("instances") if isinstance(document, dict) else None
    if not isinstance(instances, dict):
        raise RuntimeError("ecc_prize records.json: no instances table")
    for name in ALL_TARGETS:
        instance = instances.get(name)
        if not isinstance(instance, dict):
            raise RuntimeError(f"ecc_prize records.json: target missing: {name}")
        try:
            actual = digest_for(instance)
        except (KeyError, IndexError, TypeError) as error:
            raise RuntimeError(f"ecc_prize records.json: {name} is missing public curve data ({error})") from error
        expected = DIGESTS.get(name)
        if expected is None:
            raise RuntimeError(f"ecc_prize records.json: {name} has no committed digest in records.DIGESTS")
        if actual != expected:
            raise RuntimeError(
                f"ecc_prize records.json: {name} does not match its committed digest "
                f"({actual} != {expected}); regenerate with curves.py --write"
            )
    return document


def table():
    """The whole records.json document, digest-checked against DIGESTS (cached after the first read)."""
    global _CACHE
    if _CACHE is None:
        with open(RECORDS, encoding="utf-8") as stream:
            _CACHE = _validate(json.load(stream))
    return _CACHE


def instances():
    return table()["instances"]


def load_instance(name):
    """Public instance data for one target: {"name","bits","p","a","b","n","P","Q","reference"}."""
    data = instances().get(name)
    if data is None:
        raise KeyError(f"unknown ecc_prize target: {name!r}")
    return data


def reference(name):
    """{"baseline_seconds": float|None, "expected_iterations": float} for one target."""
    return load_instance(name).get("reference", {})


def load():
    """{target: reference baseline seconds} -- the per-target value a candidate is compared against."""
    known = instances()
    return {name: known[name].get("reference", {}).get("baseline_seconds") for name in ALL_TARGETS if name in known}


def fetch():
    """Re-read the committed ladder. Nothing is downloaded: the instances are generated offline."""
    global _CACHE
    _CACHE = None
    return load()


if __name__ == "__main__":
    doc = table()
    print(f"{len(doc['instances'])} ladder instances, generated {doc.get('generated_at')}")
    for name in ALL_TARGETS:
        inst = doc["instances"][name]
        ref = inst.get("reference", {})
        print(
            f"  {name:17} bits={inst['bits']:3} n={inst['n']} "
            f"expected_iterations={ref.get('expected_iterations'):.0f} baseline={ref.get('baseline_seconds')}"
        )
