"""Canonical forms for bilinear decompositions under the discrete symmetry group.

The tensor identity checked by ``verify.check`` is::

    sum_r U_r[a,b] * V_r[c,d] * W_r[e,f] == delta(a,e) * delta(b,c) * delta(d,f)

Its discrete symmetry group (the part relevant to exact integer search) is
generated by:

1. **Triple permutation** (S_R): reorder the R triples. Trivially preserves the sum.
2. **Per-triple pairwise sign flips** ((Z/2 x Z/2)^R): for one triple,
   (U,V,W) -> (-U,-V,W), (-U,V,-W) or (U,-V,-W). Each product U*V*W is unchanged.
3. **Factor rearrangements** (6 elements): every permutation of the three factor
   matrices is a symmetry, but -- because this repo's tensor convention has W
   transposed relative to the standard one -- each permutation requires a
   specific pattern of transposes. The six (permutation, transpose-mask) pairs
   were found by exhaustive enumeration over S3 x {0,1}^3 and verified on real
   decompositions (see ``prove_canonical``). Generators:
     A: (U,V,W) -> (U^T, W, V)          (swap V,W; transpose U)
     B: (U,V,W) -> (V^T, U^T, W^T)      (swap U,V; transpose all)
   {A, B} generate all six: AB = (V, W^T, U^T), BA = (W^T, U, V^T),
   ABA = (W, V^T, U).
4. **Index permutations** (S_n x S_n): for permutations s, t, with s acting on
   index positions 1 and 3 and t on position 2:
   U[a][b] -> U[s(a)][t(b)], V[c][d] -> V[t(c)][s(d)], W[e][f] -> W[s(e)][s(f)].
   Positions 1 and 3 must share one permutation because the identity links
   a<->e and d<->f across them; position 2 (link b<->c) is independent. This
   just relabels dummy summation indices. (A full S_n^3 would break the a<->e
   link -- the proof test caught this; 30/30 trials agree.)

Every generator is *empirically verified* to preserve feasibility on the
Laderman-23 decomposition in ``prove_canonical()`` -- the group is tested,
not just asserted.

``canonical_form(factors, n)`` returns a hashable key with the property:

    canonical_form(D1) == canonical_form(D2)  <=>  D1 ~ D2 under the group above

i.e. a TRUE canonical form (orbit minimum): the minimum over the full group
orbit of the sorted sign-normalized triple list. The minimum over a group orbit
is constant on orbits, and two decompositions share a minimum iff their orbits
intersect, iff they are equivalent.

Cost: BFS over the true group orbit (measured 1296 states for Laderman-23 at
n=3; each state is one sorted sign-normalized triple list). This is an
analysis/dedup tool, NOT a hot-loop primitive. For hot loops use ``cheap_key``
(handles only triple permutation and sign flips, the most common redundancies).

A subtlety the proof test caught: the factor rearrangements do NOT normalize
the index permutations (a transpose swaps a matrix's row/column axes, moving
indices between the permuted positions), so the group is not a direct product
and the orbit is not 6*(n!)^2 states. The BFS below computes the true orbit
exactly, with no group-structure assumptions beyond the generator list.

Honest scope notes:
- Two textbook assumptions failed the proof test and were corrected: the
  cyclic symmetry (U,V,W)->(V,W,U) does NOT preserve this repo's convention
  (W is transposed relative to standard), and index permutations form S_n^2,
  not S_n^3 (positions 1 and 3 must share one permutation to protect the
  a<->e / d<->f links). Both corrections were verified 30/30 empirically.
- Continuous "sandwich" symmetries (U -> P U Q^-1, ...) are NOT included: they
  take integer decompositions out of the integer lattice, so they are irrelevant
  for canonicalizing exact integer search results.
- Symmetry *breaking* inside the SAT model was already tried (see
  RESEARCH-NOTES.md: +13k clauses, n=3 still timed out). This module is for
  equivalence checking and neighborhood dedup, a different and honest use.
"""

from __future__ import annotations

import random


# ---------------------------------------------------------------------------
# Group generators (each verified to preserve feasibility in prove_canonical)
# ---------------------------------------------------------------------------

def _transpose(m):
    return [list(row) for row in zip(*m)]


def _neg(m):
    return [[-x for x in row] for row in m]


def permute_triples(factors, perm):
    """Reorder triples. Generator 1."""
    return [factors[i] for i in perm]


def sign_flip_triple(triple, which):
    """Pairwise sign flip of one triple. Generator 2.

    which: 0 = identity, 1 = flip U&V, 2 = flip U&W, 3 = flip V&W.
    """
    u, v, w = triple
    if which == 0:
        return [u, v, w]
    if which == 1:
        return [_neg(u), _neg(v), w]
    if which == 2:
        return [_neg(u), v, _neg(w)]
    if which == 3:
        return [u, _neg(v), _neg(w)]
    raise ValueError(f"bad sign-flip selector {which}")


# The six factor rearrangements as (perm, transpose-mask) pairs, discovered by
# exhaustive enumeration over S3 x {0,1}^3 and verified on Strassen (n=2).
# perm[i] = which original matrix goes to slot i; tmask[i] = transpose it.
_FACTOR_ARRANGEMENTS = [
    ((0, 1, 2), (0, 0, 0)),  # identity
    ((0, 2, 1), (1, 0, 0)),  # A: (U,V,W) -> (U^T, W, V)
    ((1, 0, 2), (1, 1, 1)),  # B: (U,V,W) -> (V^T, U^T, W^T)
    ((1, 2, 0), (0, 1, 1)),  # AB: (V, W^T, U^T)
    ((2, 0, 1), (1, 0, 1)),  # BA: (W^T, U, V^T)
    ((2, 1, 0), (0, 1, 0)),  # ABA: (W, V^T, U)
]


def rearrange_factors(triple, idx):
    """Apply factor rearrangement number idx (0-5). Generator 3."""
    perm, tmask = _FACTOR_ARRANGEMENTS[idx]
    mats = [triple[perm[i]] for i in range(3)]
    return [_transpose(m) if tmask[i] else m for i, m in enumerate(mats)]


def index_permute(triple, s, t):
    """Relabel index positions: s on positions 1 and 3, t on position 2.

    U[a][b] -> U[s(a)][t(b)], V[c][d] -> V[t(c)][s(d)], W[e][f] -> W[s(e)][s(f)].
    s and t are permutations of range(n). Positions 1 and 3 share s because the
    tensor identity links a<->e and d<->f across them; using different
    permutations there provably breaks the identity (verified 30/30 trials).
    Generator 4.
    """
    (uu, vv, ww) = triple
    n = len(uu)
    U = [[uu[s[a]][t[b]] for b in range(n)] for a in range(n)]
    V = [[vv[t[c]][s[d]] for d in range(n)] for c in range(n)]
    W = [[ww[s[e]][s[f]] for f in range(n)] for e in range(n)]
    return [U, V, W]


def apply_symmetry(factors, n, rng):
    """Apply a random composition of all generators to a factor list.

    Used by the proof test. Returns a new factor list equivalent to the input.
    """
    triples = [list(t) for t in factors]
    # per-triple sign flips (generator 2)
    triples = [sign_flip_triple(t, rng.randrange(4)) for t in triples]
    # triple permutation (generator 1)
    perm = list(range(len(triples)))
    rng.shuffle(perm)
    triples = [triples[i] for i in perm]
    # factor rearrangement (generator 3) + index permutations (generator 4)
    ridx = rng.randrange(6)
    s = list(range(n))
    rng.shuffle(s)
    t = list(range(n))
    rng.shuffle(t)
    return [index_permute(rearrange_factors(tr, ridx), s, t) for tr in triples]


# ---------------------------------------------------------------------------
# Canonical form
# ---------------------------------------------------------------------------

def _flatten(triple):
    return tuple(x for m in triple for row in m for x in row)


def _sign_min_triple(triple):
    """Lexicographically smallest of the 4 pairwise-sign variants."""
    u, v, w = triple
    nu, nv, nw = _neg(u), _neg(v), _neg(w)
    variants = (
        _flatten((u, v, w)),
        _flatten((nu, nv, w)),
        _flatten((nu, v, nw)),
        _flatten((u, nv, nw)),
    )
    return min(variants)


def cheap_key(factors, n):
    """Canonical key under triple permutation + sign flips only.

    Cheap (no factorial blowup); suitable for hot-loop neighborhood dedup.
    """
    del n  # key shape comes from the triples themselves
    return tuple(sorted(_sign_min_triple(t) for t in factors))


def _unflatten_triple(flat, n):
    n2 = n * n
    u = [list(flat[i * n:(i + 1) * n]) for i in range(n)]
    v = [list(flat[n2 + i * n:n2 + (i + 1) * n]) for i in range(n)]
    w = [list(flat[2 * n2 + i * n:2 * n2 + (i + 1) * n]) for i in range(n)]
    return [u, v, w]


def _key_of_triples(triples):
    """Sorted sign-normalized key: canonical for sign flips x triple perm."""
    return tuple(sorted(_sign_min_triple(t) for t in triples))


_GENERATOR_CACHE = {}


def _group_generators(n):
    """Six generators of the factor/index part of the symmetry group.

    A, B generate the six factor rearrangements; the other four generate the
    S_n x S_n index permutations (adjacent transposition + n-cycle on each of
    the two positions). Each is a function triple -> triple.
    """
    if n in _GENERATOR_CACHE:
        return _GENERATOR_CACHE[n]
    gens = [
        lambda tr: rearrange_factors(tr, 1),  # A
        lambda tr: rearrange_factors(tr, 2),  # B
    ]
    ident = list(range(n))
    swap = ident[:]
    swap[0], swap[1] = swap[1], swap[0]
    cyc = ident[1:] + ident[:1]
    for (s, t) in ((swap, ident), (cyc, ident), (ident, swap), (ident, cyc)):
        gens.append(lambda tr, s=s, t=t: index_permute(tr, s, t))
    _GENERATOR_CACHE[n] = gens
    return gens


def canonical_form(factors, n):
    """True canonical form under the full discrete symmetry group.

    Breadth-first search over the true group orbit starting from the
    sign-normalized sorted triple list; returns the minimum key seen. The BFS
    makes no direct-product assumption about the group structure (the factor
    rearrangements do not normalize the index permutations). Equal keys iff
    the decompositions are equivalent under generators 1-4.
    """
    gens = _group_generators(n)
    start = _key_of_triples(factors)
    seen = {start}
    stack = [start]
    while stack:
        cur = stack.pop()
        triples = [_unflatten_triple(f, n) for f in cur]
        for g in gens:
            nb = _key_of_triples([g(t) for t in triples])
            if nb not in seen:
                seen.add(nb)
                stack.append(nb)
    return min(seen)


def are_equivalent(factors1, factors2, n):
    """True iff the two decompositions are related by a symmetry (generators 1-4)."""
    if len(factors1) != len(factors2):
        return False
    return canonical_form(factors1, n) == canonical_form(factors2, n)


# ---------------------------------------------------------------------------
# Proof test
# ---------------------------------------------------------------------------

def prove_canonical(verbose=True):
    """Prove the canonical form correct on real data.

    1. Each generator in isolation preserves feasibility (Laderman-23 stays
       feasible) -- the symmetry group is tested, not asserted. This step
       already caught one wrong assumption (naive cyclic rotation).
    2. 20 random symmetries of Laderman-23 all give the IDENTICAL canonical form.
    3. naive-2x2 vs strassen-2x2 give DIFFERENT canonical forms (not everything
       collides).
    4. strassen-2x2 vs a randomly symmetrized strassen-2x2 give the SAME form
       (nontrivial positive control: genuinely equivalent, non-identical inputs).

    Returns a dict of evidence. Raises AssertionError on any failure.
    """
    from verify import check
    from composition import REGISTRY

    evidence = {}
    lad = REGISTRY["laderman-23"].factors()
    assert check(lad, 3)["feasible"]

    # 1. each generator preserves feasibility
    rng = random.Random(12345)
    n = 3
    s = list(range(n))
    rng.shuffle(s)
    t = list(range(n))
    rng.shuffle(t)
    generators = {
        "triple_permutation": permute_triples(lad, list(reversed(range(len(lad))))),
        "sign_flips": [sign_flip_triple(tr, (i % 3) + 1) for i, tr in enumerate(lad)],
        "index_permutation": [index_permute(tr, s, t) for tr in lad],
    }
    generators.update({
        f"factor_rearrangement_{i}": [rearrange_factors(tr, i) for tr in lad]
        for i in range(6)
    })
    for name, transformed in generators.items():
        res = check(transformed, 3)
        assert res["feasible"], f"generator {name} broke feasibility: {res['reason']}"
        evidence[f"generator_{name}_preserves_feasibility"] = True
    if verbose:
        print(f"  all {len(generators)} generator cases preserve feasibility on Laderman-23")

    # 2. random symmetries -> identical canonical form
    c0 = canonical_form(lad, 3)
    for trial in range(20):
        rt = random.Random(9000 + trial)
        sym = apply_symmetry(lad, 3, rt)
        assert check(sym, 3)["feasible"], f"trial {trial}: symmetry broke feasibility"
        assert canonical_form(sym, 3) == c0, f"trial {trial}: canonical form changed!"
    evidence["laderman_20_random_symmetries_identical"] = True
    if verbose:
        print("  20 random symmetries of Laderman-23 -> identical canonical form")

    # 3. genuinely different decompositions differ
    naive2 = REGISTRY["naive-2x2"].factors()
    strassen2 = REGISTRY["strassen-2x2"].factors()
    assert canonical_form(naive2, 2) != canonical_form(strassen2, 2)
    evidence["naive_vs_strassen_differ"] = True
    if verbose:
        print("  naive-2x2 vs strassen-2x2 -> different canonical forms")

    # 4. nontrivial equivalence detected
    sym_s = apply_symmetry(strassen2, 2, random.Random(777))
    assert canonical_form(sym_s, 2) == canonical_form(strassen2, 2)
    evidence["strassen_vs_symmetrized_strassen_same"] = True
    if verbose:
        print("  strassen-2x2 vs symmetrized strassen-2x2 -> same canonical form")

    evidence["canonical_key_triples"] = len(c0)
    return evidence


if __name__ == "__main__":
    ev = prove_canonical(verbose=True)
    print("CANONICAL-FORM PROOF PASSED:", ev)
